### ISSUE TITLE
[FD] Ideas #0: food

### ISSUE THREAD

**Issue by richelbilderbeek** [tresinformal/game#219]
There is the idea that a player can gather food, similar to [https://agar.io/](https://agar.io/).

With food, a player can grow and/or change colors, but the exact mechanisms can be determined freely.

Part of the logic of food is already in, such as:

  * [x] #121 : Food has a color
  * [x]  #39 : the `game` has food
  * [x] #206 : add `operator<<` for food
  * [x] #170 : add `to_str` for `food_type`
   
Maybe all zero food items are even already drawn :confused:
