### ISSUE TITLE
[PRS] Idea #-1: Rock-Paper-Scissor dynamics

### ISSUE THREAD

**Issue by richelbilderbeek** [tresinformal/game#221]
Depends on:

 * [ ] #229 convert RGB values to hue
 * [ ] #230 determine winner from two hues
 * [ ] #231 determine winner from two players
 * [ ] #232 determine loser from two hues
 * [ ] #233 make winning PRS player bigger
 * [ ] #234 make losing PRS player smaller

Ye olde idea is that the red/green/blue color of the player is equivalent to paper/rock/scissors. So, a player with the winning color can eat/damage a bigger player of the losing color. 

Curerntly, a player of the losing color dies, but this idea is not yet taken further.
