### ISSUE TITLE
[STUN] By pressing a key, player 1 is stunned

### ISSUE THREAD

**Issue by richelbilderbeek** [tresinformal/game#224]
Depends on

 * [x] #225 Create an action to stun a player
 * [x] #226 game responds to stun action
 * [x] #242 Pressing 1 results in a stun action

Currently, we can stun a player from code (#220), but not yet make this happen in the game.

As a first step, make it so that a key press (e.g. ´1´) stuns player -say- 1.

Make this test come true:

```c++
  //#define FIX_ISSUE_224
  #ifdef FIX_ISSUE_224
  // Pressing 1 stuns player 1
  {
    game_view g;
    assert(!is_nth_player_stunned(g, 0));
    g.press_key(sf::Keyboard::Num1);
    g.process_events(); // Needed to process the event
    assert(is_nth_player_stunned(g, 0));
  }
  #endif // FIX_ISSUE_224
```

**Comment by richelbilderbeek** [comment]
Hey @ollyturner, when we working on #267, suddenly the tests below broke at the line indicated below, so we added `#ifdef` to disable the tests again. Could you take a look? Of course, we would be happy to help. Thanks, Richel and Theo

```
   #ifdef FIX_ISSUE_224
  // #define FIX_ISSUE_224
  // Pressing 1 stuns player 1
  {
    game_view g;
    assert(!is_nth_player_stunned(g, 0));
    g.press_key(sf::Keyboard::Num1);
    g.process_events(); // Needed to process the event
    assert(is_nth_player_stunned(g, 0));
  }
  // Pressing the wrong key does not stun a player
  {
    game_view g;
    assert(!is_nth_player_stunned(g, 0));
    g.press_key(sf::Keyboard::Num2);
    g.process_events(); // Needed to process the event
    assert(!is_nth_player_stunned(g, 0)); // assertion failed here
  }
  #endif
```

**Comment by ollyturner** [comment]
We didn't find a problem.
